apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-wordpress
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: wordpress
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
