apiVersion: v1
kind: Service
metadata:
  name: wordpress-http
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000